(package! latex-preview-pane)
(package! modus-themes)
(package! ef-themes)
(package! telega)
(package! scala-repl)
(package! treesit-auto)
(package! ng2-mode)
(package! spacemacs-theme)
(package! standard-themes)
(package! evil-cleverparens)
(package! flycheck-rust)
(package! eglot-booster
  :recipe (:host github :repo "jdtsmith/eglot-booster"
           :files ("*")))
(disable-packages! android-mode groovy-mode nodejs-repl coffee-mode skewer-mode all-the-icons tuareg-mode idris-mode)
;; (package! mu4e-alert)
