require("plugins")
require("lsp")
require("treesitter-config")
require("keybindings")
require("configs")
require("colorscheme")
require("statusline")
require("fidget").setup({ text = { spinner = "moon" } })
require("nvim-navic").setup({})
require("nvim-autopairs").setup({})
require("lsp-inlayhints").setup()
require("hlargs").setup()
require("colorizer").setup()
require("dirbuf").setup({})
