set undofile
syntax on
filetype plugin indent on
set shiftwidth=4
set shiftround
set tabstop=8
set softtabstop=4
set smarttab
set cursorline
set noexpandtab
set clipboard+=unnamedplus
set showcmd
set number
set relativenumber
set hidden
set background=dark
set termguicolors
set mouse=a
set noshowmode
set signcolumn=yes
set completeopt=menuone,noselect
set shortmess+=c
